language: php

dist: trusty

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.3
    - php: nightly
    - php: 7.4snapshot
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit