language: php

dist: trusty

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env: deps=high
    - php: nightly
    - php: 7.4snapshot
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
    
script:
  - ./vendor/bin/phpunit